import { jsPDF } from 'jspdf';
import type { PayrollItem, Staff } from '@bizmanager/types';
import { formatCurrency, getMonthName } from '@bizmanager/utils';
import { downloadBlob } from './download';

export interface PayslipData {
  companyName: string;
  month: number;
  year: number;
  staff: Pick<Staff, 'full_name' | 'role_title' | 'phone' | 'email'>;
  item: PayrollItem;
}

function renderPayslipPage(doc: jsPDF, data: PayslipData) {
  const { companyName, month, year, staff, item } = data;
  const period = `${getMonthName(month)} ${year}`;

  doc.setFontSize(18);
  doc.text(companyName, 20, 24);
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text('Salary Payslip', 20, 32);
  doc.setTextColor(0);

  doc.setFontSize(11);
  doc.text(`Period: ${period}`, 20, 46);
  doc.text(`Employee: ${staff.full_name}`, 20, 54);
  doc.text(`Role: ${staff.role_title}`, 20, 62);
  if (staff.phone) doc.text(`Phone: ${staff.phone}`, 20, 70);

  let y = 86;
  const row = (label: string, value: string, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.text(label, 20, y);
    doc.text(value, 190, y, { align: 'right' });
    y += 10;
  };

  doc.setDrawColor(220);
  doc.line(20, 78, 190, 78);

  row('Basic Salary', formatCurrency(item.basic_salary));
  if (item.allowance > 0) row('Allowances', formatCurrency(item.allowance));
  if (item.overtime > 0) row('Overtime', formatCurrency(item.overtime));
  if (item.advance > 0) row('Advances', `-${formatCurrency(item.advance)}`);
  row('EPF (Employee 8%)', `-${formatCurrency(item.epf_employee)}`);
  if (item.deductions > 0) row('Other Deductions', `-${formatCurrency(item.deductions)}`);
  if (item.no_pay_deduction > 0) row('No-Pay Deduction', `-${formatCurrency(item.no_pay_deduction)}`);

  doc.line(20, y - 4, 190, y - 4);
  row('Net Payable', formatCurrency(item.net_payable), true);

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by BizManager · Confirm statutory deductions with your accountant', 20, 280);
}

function buildPayslipDoc(data: PayslipData): jsPDF {
  const doc = new jsPDF();
  renderPayslipPage(doc, data);
  return doc;
}

export function downloadPayslipPdf(data: PayslipData) {
  const slug = data.staff.full_name.replace(/\s+/g, '-').toLowerCase();
  const filename = `payslip-${slug}-${data.year}-${String(data.month).padStart(2, '0')}.pdf`;
  const blob = buildPayslipDoc(data).output('blob');
  downloadBlob(blob, filename);
}

export function downloadAllPayslipsPdf(items: PayslipData[]) {
  if (!items.length) return;
  const { month, year } = items[0];
  const doc = new jsPDF();
  items.forEach((data, index) => {
    if (index > 0) doc.addPage();
    renderPayslipPage(doc, data);
  });
  const filename = `payslips-all-${year}-${String(month).padStart(2, '0')}.pdf`;
  downloadBlob(doc.output('blob'), filename);
}

export function buildPayslipWhatsAppMessage(data: PayslipData): string {
  const { companyName, month, year, staff, item } = data;
  const period = `${getMonthName(month)} ${year}`;
  return [
    `${companyName} — Payslip`,
    `Period: ${period}`,
    `Employee: ${staff.full_name}`,
    `Basic: ${formatCurrency(item.basic_salary)}`,
    `EPF (8%): ${formatCurrency(item.epf_employee)}`,
    `Net Pay: ${formatCurrency(item.net_payable)}`,
    '',
    'Sent via BizManager',
  ].join('\n');
}
