import { jsPDF } from 'jspdf';
import type { Customer, DashboardSummary, Supplier } from '@bizmanager/types';
import type { CategoryChartItem } from '@bizmanager/utils';
import { formatCurrency, PDF_REPORT_LABELS } from '@bizmanager/utils';
import type { Language } from '@bizmanager/i18n';
import { downloadBlob } from './download';

export interface ReportExportData {
  companyName: string;
  periodLabel: string;
  language?: Language;
  summary: DashboardSummary;
  customers: Customer[];
  suppliers: Supplier[];
  expenseBreakdown?: CategoryChartItem[];
  incomeBreakdown?: CategoryChartItem[];
}

export function downloadReportPdf(data: ReportExportData) {
  const doc = new jsPDF();
  const lang = data.language ?? 'en';
  const labels = PDF_REPORT_LABELS[lang];
  const { companyName, periodLabel, summary, customers, suppliers, expenseBreakdown, incomeBreakdown } = data;

  doc.setFontSize(18);
  doc.text(companyName, 20, 24);
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`${labels.reportTitle} — ${periodLabel}`, 20, 32);
  doc.setTextColor(0);

  let y = 48;
  const metric = (label: string, value: string) => {
    doc.setFont('helvetica', 'normal');
    doc.text(label, 20, y);
    doc.setFont('helvetica', 'bold');
    doc.text(value, 190, y, { align: 'right' });
    y += 10;
  };

  metric(labels.income, formatCurrency(summary.todayIncome));
  metric(labels.expenses, formatCurrency(summary.todayExpenses));
  metric(labels.netProfit, formatCurrency(summary.netProfit));
  metric(labels.receivables, formatCurrency(summary.receivables));
  metric(labels.payables, formatCurrency(summary.payables));

  const writeBreakdown = (title: string, items?: CategoryChartItem[]) => {
    if (!items?.length || y > 250) return;
    y += 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(title, 20, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    for (const item of items.slice(0, 8)) {
      if (y > 280) break;
      doc.text(item.label.slice(0, 40), 20, y);
      doc.text(formatCurrency(item.value), 190, y, { align: 'right' });
      y += 8;
    }
  };

  writeBreakdown(labels.expensesByCategory, expenseBreakdown);
  writeBreakdown(labels.incomeByCategory, incomeBreakdown);

  y += 6;
  if (y < 240) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(labels.topReceivables, 20, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    for (const c of customers.slice(0, 5)) {
      if (y > 280) break;
      doc.text(c.name, 20, y);
      doc.text(formatCurrency(c.current_balance), 190, y, { align: 'right' });
      y += 8;
    }
  }

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by BizManager', 20, 290);

  const filename = `report-${periodLabel.replace(/\s+/g, '-').toLowerCase()}.pdf`;
  downloadBlob(doc.output('blob'), filename);
}
