import { jsPDF } from 'jspdf';
import type { Customer, DashboardSummary, Supplier, Transaction } from '@bizmanager/types';
import { formatCurrency } from '@bizmanager/utils';
import { downloadBlob } from './download';

export interface ReportExportData {
  companyName: string;
  periodLabel: string;
  summary: DashboardSummary;
  customers: Customer[];
  suppliers: Supplier[];
  transactions: Transaction[];
}

export function downloadReportPdf(data: ReportExportData) {
  const doc = new jsPDF();
  const { companyName, periodLabel, summary, customers, suppliers, transactions } = data;

  doc.setFontSize(18);
  doc.text(companyName, 20, 24);
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Business Report — ${periodLabel}`, 20, 32);
  doc.setTextColor(0);

  let y = 48;
  const metric = (label: string, value: string) => {
    doc.setFont('helvetica', 'normal');
    doc.text(label, 20, y);
    doc.setFont('helvetica', 'bold');
    doc.text(value, 190, y, { align: 'right' });
    y += 10;
  };

  metric('Income', formatCurrency(summary.todayIncome));
  metric('Expenses', formatCurrency(summary.todayExpenses));
  metric('Net Profit', formatCurrency(summary.netProfit));
  metric('Cash Balance', formatCurrency(summary.cashBalance));
  metric('Receivables', formatCurrency(summary.receivables));
  metric('Payables', formatCurrency(summary.payables));

  y += 6;
  doc.setFont('helvetica', 'bold');
  doc.text('Recent Transactions', 20, y);
  y += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);

  for (const tx of transactions.slice(0, 12)) {
    if (y > 270) break;
    const label = `${tx.transaction_date} · ${tx.type} · ${tx.description ?? tx.category ?? '—'}`;
    doc.text(label.slice(0, 55), 20, y);
    doc.text(formatCurrency(tx.amount), 190, y, { align: 'right' });
    y += 8;
  }

  y += 6;
  if (y < 240) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Top Receivables', 20, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    for (const c of customers.slice(0, 5)) {
      if (y > 280) break;
      doc.text(c.name, 20, y);
      doc.text(formatCurrency(c.current_balance), 190, y, { align: 'right' });
      y += 8;
    }
  }

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by BizManager', 20, 290);

  const filename = `report-${periodLabel.replace(/\s+/g, '-').toLowerCase()}.pdf`;
  downloadBlob(doc.output('blob'), filename);
}
